### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by frewsxcv** [linovia/sentry-hipchat#29]
There are a lot of changes, and for some reason a new version hasn't been released in a long time

**Comment by tobych** [comment]
On which note, is there a recent commit that's reasonable to use in production?

**Comment by streeter** [comment]
We're using 18ba4e1 in production, and it seems to be working great.

**Comment by dcramer** [comment]
Pushed 0.6.0

**Comment by tobych** [comment]
Thanks Chris, David.
